---
language: ruby

rvm:
  - 1.8.7
  - 2.1.9

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.8.0"
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
    - PUPPET_GEM_VERSION="~> 4.8.0"
    - PUPPET_GEM_VERSION="~> 4.9.0"
    - PUPPET_GEM_VERSION="~> 4.10.0"
    - PUPPET_GEM_VERSION="~> 4"

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.8.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.9.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.10.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4"

notifications:
  email: false
